### ISSUE TITLE
[Error]X1C 2016's battery status wrong

### ISSUE THREAD

**Issue by londbell** [akimitwo/hackintosh#1]
Always show 1%

**Comment by osmaniax** [comment]
uuum,my X1C(4th)'s battery level is ok.
and my bios version is "N1FET59W(1.33)".
pls check version.

if your version is newer bios, you make your origin acpi files(dsdt,ssdt).

**Comment by londbell** [comment]
I've checked your SSDT-BATC.aml and SSDT-BATT, basically it is the same file from https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore.I think it can't work on your machine;Because the battery system is totally different between T460s and X1C G4,you must disable bat1.
